### ISSUE TITLE
MobilenetV1 conversion from tfjs graph model to frozen model problem with quantization

### ISSUE THREAD

**Issue by pjaholkowski** [patlevin/tfjs-to-tf#26]
Hi

I have models (not mine) in tfjs graph model it is MobilenetV1 in float and quantized to int16 and int8.
The original with float after conversion works okay but that two other ones are inproperly converted. 
You can see that by comparing original graph model and generated model in Netron.
I put original graph model as attachment

![original_model](https://user-images.githubusercontent.com/41017674/99403564-e2f38300-28ea-11eb-9a44-f9349402887b.png)
![converted_model](https://user-images.githubusercontent.com/41017674/99403588-eab32780-28ea-11eb-87d8-f854d6c7fe68.png)
[mobilenet_quant2_075_stride16.zip](https://github.com/patlevin/tfjs-to-tf/files/5554129/mobilenet_quant2_075_stride16.zip)

**Comment by patlevin** [comment]
This seems tobe an issue with tensorflowjs.

The reason for the difference is data loss during de-quantisation of the weights which leads to all packed bias values being zero after loading. The optimiser will then happily drop the `BiasAdd`-operation, since it detects a no-op due to the bias values being zero.

I will do some further investigating and fix the problem in tensorflowjs if possible.

**Comment by patlevin** [comment]
I have identified the problem in tensorflowjs and will submit a pull request to fix the problem.

I'll let you know once the tensorflowjs has merged the changes. I could add a workaround here, but I feel it's better to fix the problem at its root, especially since that will benefit every user of tensorflowjs.

Thanks for bringing the problem to my attention, though!

**Comment by pjaholkowski** [comment]
OK, thank you

**Comment by patlevin** [comment]
The fix for tensorflowjs has been approved and a future version (maybe even the next one?) will solve the issue.

It took a while due to a US holiday, but eventually the issue got sorted. It's not merged into the master branch yet, so I keep this issue open.

**Comment by pjaholkowski** [comment]
That's good news. Thank you for letting me know

**Comment by patlevin** [comment]
The bugfix has been merged into TFJS master just now: [https://github.com/tensorflow/tfjs/pull/4285](Pull Request).

It should be part of the next TFJS release, which would fix this issue. You can also install the TFJS master version to get the bug fixed immediately.
