### ISSUE TITLE
Issue converting Blazepose model

### ISSUE THREAD

**Issue by anchit-sadana** [patlevin/tfjs-to-tf#37]
I get an error ``` Node 'StatefulPartitionedCall/model/depthwise_conv2d_30': Unknown input node 'StatefulPartitionedCall/model/depthwise_conv2d_29/depthwise'```  while trying to convert the Blazepose model from the TF hub from tfjs to Tensorflow. Any idea how I can work around this?

**Comment by patlevin** [comment]
The issue has been fixed and you can use the latest release or simply use `pip install tfjs-graph-converter -U` to update to the latest version (1.6.1).

**Comment by anchit-sadana** [comment]
Thanks!

**Comment by hqt98** [comment]
> Thanks!

Hi, I'm having issues converting [this model](https://www.kaggle.com/models/mediapipe/blazepose-3d/frameworks/tfJs/variations/detector ) using this tool, I'm having some issues that I think is being caused by dependency versions mismatched, that cannot be solved because on my M1 machine. Did you convert this model successfully? Can you share your steps and dependency versions at the time?
