### ISSUE TITLE
Depth error while converting graph model to frozen

### ISSUE THREAD

**Issue by dasmehdix** [patlevin/tfjs-to-tf#42]
Hi. I am trying to convert a TFJS Graph model to TF Frozen model. Inside TFJS Graph model(`model.json`) there is not a `weightsManifest `attribute. There is `weightSpecs `attribute instead of `weightsManifest`. So, I converted `weigthSpecs `to `weightsManifest `and add a `path` attribute inside `weightsManifest` as shown in below image.
![converting](https://user-images.githubusercontent.com/52709620/204090128-4626b18a-7926-4586-9bdd-6ed82f62a9ac.jpg)

After, I have tried to convert TFJS Graph model to frozen model but I get this error.
```
TensorFlow.js Graph Model Converter

Graph model:    model2.json
Output:         converted.pb
Target format:  tf_frozen_model

Converting.... Error: Depth of input (1633707611) is not a multiple of input depth of filter (3) for '{{node model/conv2d/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/device:CPU:0"](model/zero_padding2d/Pad, Const_114:0)' with input shapes: [1751275624,1818515716,1819108088,1633707611], [3,3,3,24].
```
As I understand model is corrupted, how can I convert this model to frozen?

**Comment by patlevin** [comment]
> As I understand model is corrupted, how can I convert this model to frozen?

I don't know that the model is broken. There is a way in TFJS to save a model to local storage (i.e. in the browser's DB) that uses the `weightSpec` field instead of `weightManifest`. That's because the browser's local storage doesn't have file paths, whereas weight manifest does.

You can try and load the model using TFJS in the browser and see whether that works first. To be of any further help I would need to take a look at the model.json.
