### ISSUE TITLE
tenslrflow.GraphDef has no field named "keras_version"

### ISSUE THREAD

**Issue by PuddingPengChen** [patlevin/tfjs-to-tf#5]
hi,patlevin!
Thank you for sharing your project,it was very useful.
but when I test the model here
https://github.com/google/tfjs-mnist-workshop/tree/master/model
It export error: 
Message type"tensorflow.GraphDef" has no field named "keras_version".
I test many models, such as: ml5js-model here:
https://github.com/ml5js/ml5-data-and-models
all models has the same problem.

**Comment by patlevin** [comment]
The problem is that these models aren't *graph* models. The converter only supports TFJS graph models (hence the name 😉).
The models you tried to convert are *layer* models. You don't need this converter to load layer models - tfjs can load them out-of-the-box like so:

~~~py
import os
import tensorflowjs as tfjs

model = tfjs.converters.load_keras_model('path-to-model.json')
~~~

**Comment by PuddingPengChen** [comment]
Thank you very much! Your advice if of great help to me :smile:   :+1:

**Comment by patlevin** [comment]
Glad I could help😃
